---
- name: install and run the Lamp stack on centos 7.
  hosts: salahdin
  become: yes
  tasks:

  - name: Install Apache Latest :()
    yum:
      name: httpd
      state: latest
  - name: start and enable Apache :X
    service:
      name: httpd
      state: started
      enabled: yes



  - name: Install MySQl Latest 3>
    yum:
      name: 
      - mysql-server
      - mysql
      state: latest
  - name: start and enable mysql ^^
    service:
      name: mysqld.service
      state: started
      enabled: yes


  - name: Install PHP Latest :)
    yum:
      name:
      - php 
      - php-mysqlnd
      - php-mbstring
      - php-xml
      - php-opcache
      - php-fpm
      state: latest
  - name: start and enable PHP  _**_
    service:
      name: php-fpm
      state: started
      enabled: yes

  - name: open port 80/tcp in FW :()
    firewalld:
      port: 80/tcp
      permanent: true
      state: enabled

  - name:  open port 443/tcp in FW :)
    firewalld:
      port: 443/tcp
      permanent: true
      state: enabled


  - name:  open https in FW  :D
    firewalld:
      service: https
      permanent: true
      state: enabled

  - name: open http in FW  :O
    firewalld:
      service: http
      permanent: true
      state: enabled


  - name: Restart the firewalld service to load in the firewall changes
    service:
      name: firewalld
      state: restarted



  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted

  - name: Copying sample php page in the LAMP :*
    copy:
      src: /var/www/html/index.php
      dest: /var/www/html/index.php 

  - name: FinallyYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY to test that it can reach the php page from the playbook .
    uri:
      url: http://192.168.10.130/index.php
      status_code: 200
